<a href="https://colab.research.google.com/github/ashokteja123/Data-Analysis-Essentials/blob/main/Week_1%26_2_DAE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
states= ["AP","TG","KA","TN","KL"]

In [ ]:
literacy=[67.4,66.5,75.4,80.1,94.0]

In [ ]:
total=0
for x in literacy :
  total += x

In [ ]:
average = total/len(literacy)
print(average)

76.67999999999999


In [ ]:
import numpy as np


In [ ]:
print(np.version)

<module 'numpy.version' from '/usr/local/lib/python3.12/dist-packages/numpy/version.py'>


In [ ]:
literacy =np.array([67.4,66.5,54.6,45.3,34.3])
print(literacy)
print(type(literacy))

[67.4 66.5 54.6 45.3 34.3]
<class 'numpy.ndarray'>


In [ ]:
print(literacy.mean())

53.620000000000005


In [ ]:
print(literacy.max())

67.4


In [ ]:
print(literacy.min())

34.3


In [ ]:
print(literacy.shape)

(5,)


In [ ]:
print(np.mean(literacy))

53.620000000000005


In [ ]:
print(literacy.ndim)

1


In [ ]:
print(literacy.dtype)

float64


In [ ]:
print(literacy.size)

5


In [ ]:
zeros_arr = np.zeros((3,3))
print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ones_arr = np.ones((2,4))
print(ones_arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
random_arr = np.random.randint(1,100,(3,3))
print(random_arr)

[[90 86  8]
 [17 95 15]
 [91 32 10]]


In [ ]:
identity = np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
spaced = np.linspace(0, 1, 10)
print(spaced)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
ranged = np.arange(1 , 50 ,5)
print(ranged)

[ 1  6 11 16 21 26 31 36 41 46]


In [ ]:
import numpy as np


SESSION 2

In [ ]:
# Cell 1 — recap array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])

In [ ]:
# Cell 2 — shape attributes
print(arr.shape)
print(arr.ndim)
print(arr.size)

(2, 3)
2
6


In [ ]:
# Cell 3 — reshape
print(arr.reshape(3,2))
print(arr.reshape(6,))
print(arr.reshape(-1,3))


[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
# Cell 4 — flatten vs ravel
print(arr.flatten())
print(arr.ravel())

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
# Cell 5 — transpose
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Cell 6 — expand and squeeze
print(np.expand_dims(arr, axis=0).shape)
print(np.squeeze(np.expand_dims(arr, axis=0)).shape)


(1, 2, 3)
(2, 3)


In [ ]:
# Cell 7 — matrix multiply teaser
A = np.random.randint(1,10,(3,4))
B = np.random.randint(1,10,(4,2))
print((A @ B).shape)

(3, 2)


In [ ]:
arr = np.arange(1, 13)   # [1,2,3,...,12]
print(arr.shape)          # (12,)



(12,)


In [ ]:
# Reshape to 3x4
print(arr.reshape(3, 4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# Reshape to 4x3
print(arr.reshape(4, 3))


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Reshape to 2x6
print(arr.reshape(2, 6))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
# Reshape to 3D
print(arr.reshape(2, 2, 3))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
print(arr.reshape(3, 5))   # ERROR — 3×5=15 ≠ 12

ValueError: cannot reshape array of size 12 into shape (3,5)

In [ ]:
# Let NumPy calculate one dimension automatically
print(arr.reshape(-1, 3))   # NumPy figures out rows = 4


In [ ]:
print(arr.reshape(3, -1))   # NumPy figures out cols = 4

In [ ]:
print(arr.reshape(2, -1, 3)) # NumPy figures out middle = 2

In [ ]:
arr2d = np.array([[1,2,3],[4,5,6]])

f = arr2d.flatten()
r = arr2d.ravel()

print(f)   # [1 2 3 4 5 6]
print(r)   # [1 2 3 4 5 6]

# Now modify and check original
f[0] = 999
r[0] = 999

print(arr2d)  # flatten: original unchanged. ravel: original CHANGED

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[999   2   3]
 [  4   5   6]]


"flatten() always gives you a brand new copy — safe but uses more memory. ravel() gives you a view of the same data — faster but modifying it changes the original. In production code this difference matters a lot."

1. Create a 1D array of 20 elements using np.arange()
   Reshape it to (4,5), (5,4), (2,2,5), and (-1,4)

2. Create a 3x4 array of ones
   Print its shape, size, ndim

3. Reshape a (3,4) array into (12,) — flatten it into 1D

4. Use flatten() and ravel() on a 2D array
   Modify the first element of each result
   Check if the original array changed

5. Predict (don't run first): what shape is np.zeros((3,4,5))?
   What is its size? What is its ndim?
   Then run and verify.

TRANSISTIONS

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Original shape:", arr.shape)     # (2,3)
print(arr)

# Transpose
print("Transposed shape:", arr.T.shape) # (3,2)
print(arr.T)

Original shape: (2, 3)
[[1 2 3]
 [4 5 6]]
Transposed shape: (3, 2)
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# 1D transpose — does nothing (important to show)
a = np.array([1, 2, 3, 4])
print(a.T.shape)    # still (4,) — 1D has no second axis to swap
print(a.T)          # same array


(4,)
[1 2 3 4]


In [ ]:
# Square matrix — rows and columns swap
sq = np.array([[1,2],[3,4],[5,6]])
print(sq.shape)     # (3,2)
print(sq.T.shape)   # (2,3)

(3, 2)
(2, 3)


In [ ]:
# np.transpose() — same as .T for 2D
print(np.transpose(arr))

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
A = np.random.randint(1, 10, (3, 4))
B = np.random.randint(1, 10, (4, 2))

print("A shape:", A.shape)        # (3,4)
print("B shape:", B.shape)        # (4,2)
print("A@B shape:", (A @ B).shape) # (3,2)

# Why A @ A.T is always possible:
print("A@A.T shape:", (A @ A.T).shape) # (3,3) always square

A shape: (3, 4)
B shape: (4, 2)
A@B shape: (3, 2)
A@A.T shape: (3, 3)


A is (3×4), A.T is (4×3), multiplying gives (3×3). This pattern is used in neural networks millions of times per second."

Expand Dims & Squeeze

In deep learning, models don't process one image at a time — they process batches. An image is shape (224,224,3). A batch of 32 images is (32,224,224,3). That extra 32 at the front is added by expand_dims. You will do this every single time you feed an image to a neural network.

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Original:", arr.shape)        # (2,3)


Original: (2, 3)


In [ ]:
# Add axis at position 0 — add a "batch" dimension
e0 = np.expand_dims(arr, axis=0)
print("Axis 0:", e0.shape)           # (1,2,3)

Axis 0: (1, 2, 3)


In [ ]:
# Add axis at position 1
e1 = np.expand_dims(arr, axis=1)
print("Axis 1:", e1.shape)           # (2,1,3)

Axis 1: (2, 1, 3)


In [ ]:
# Add axis at position 2
e2 = np.expand_dims(arr, axis=2)
print("Axis 2:", e2.shape)           # (2,3,1)

Axis 2: (2, 3, 1)


axis=0 adds a new outermost layer → think "batch of 1"
axis=1 adds between rows and columns → think "each row is its own group"
axis=2 adds innermost → think "each element becomes a list of 1"

Squeeze

In [ ]:
# Squeeze removes dimensions of size 1
a = np.zeros((1, 3, 1, 4))
print("Before squeeze:", a.shape)     # (1,3,1,4)

Before squeeze: (1, 3, 1, 4)


In [ ]:
s = np.squeeze(a)
print("After squeeze:", s.shape)      # (3,4) — both size-1 dims removed

After squeeze: (3, 4)


In [ ]:
# Squeeze specific axis only
s1 = np.squeeze(a, axis=0)
print("Squeeze axis 0:", s1.shape)    # (3,1,4)

Squeeze axis 0: (3, 1, 4)


In [ ]:
s2 = np.squeeze(a, axis=2)
print("Squeeze axis 2:", s2.shape)    # (1,3,4)

Squeeze axis 2: (1, 3, 4)


"squeeze() only removes dimensions whose size is 1 — it never removes a dimension that actually has data. So squeeze on a (3,4) array does nothing — there's nothing to remove."

In [ ]:
b = np.zeros((3, 4))
print(np.squeeze(b).shape)   # still (3,4) — nothing removed

(3, 4)


Sorting — quick addition

In [ ]:
marks = np.array([78, 45, 92, 63, 88, 51])

print(np.sort(marks))              # ascending by default
print(np.sort(marks)[::-1])        # descending — reverse the sorted array
print(np.argsort(marks))           # indices that would sort the array

# Real use: who is the topper?
names = ["Ravi", "Priya", "Suresh", "Anita", "Kiran", "Divya"]
rank_order = np.argsort(marks)[::-1]
print("Rank 1:", names[rank_order[0]], marks[rank_order[0]])

[45 51 63 78 88 92]
[92 88 78 63 51 45]
[1 5 3 0 4 2]
Rank 1: Suresh 92


argsort is one of the most useful NumPy functions you'll ever use. It doesn't give you the sorted values — it gives you the sorted POSITIONS. So you can rank students, rank products by sales, rank recommendations — all with one line.

In [ ]:
my_arr = [5,6,7,8,8]

In [ ]:
print(my_arr[0])

5


In [ ]:
import numpy as np

In [ ]:
import numpy as np
my_arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[10,11]]])

In [ ]:
print(my_arr.shape)

(3, 2, 2)


Week 1 Programs

In [ ]:
csk_scores = np.array([182, 156, 203, 178, 165, 190, 172])

In [ ]:
print("CSK Scores:", csk_scores)
print("Type:", type(csk_scores))
print("Data type of elements:", csk_scores.dtype)
print("Highest score:", csk_scores.max())
print("Lowest score:", csk_scores.min())
print("Average score:", csk_scores.mean())
print("csk_scores:",)

CSK Scores: [182 156 203 178 165 190 172]
Type: <class 'numpy.ndarray'>
Data type of elements: int64
Highest score: 203
Lowest score: 156
Average score: 178.0


| City | Price (₹/L) |  
|------|-------------|  
| Vizag | 102.5 |  
| Vijayawada | 101.8 |  
| Guntur | 103.2 |  
| Tirupati | 100.9 |  
| Kakinada | 102.1 |  
| Nellore | 101.5 |  

Write a program that:

Stores the prices in a NumPy array

Prints the cheapest city price

Prints the most expensive city price

Prints the average price across cities

Prints the difference between the most and least expensive

In [ ]:
cities = ["Vizag", "Vijayawada", "Guntur", "Tirupati", "Kakinada", "Nellore"]#The cities list is just for our reference. The array only holds the numbers
petrol_price = np.array([102.5, 101.8, 103.2, 100.9, 102.1, 101.5])

In [ ]:
print("Petrol Prices:", petrol_price)
print("Cheapest city price:", petrol_price.min())
print("Most expensive city price:", petrol_price.max())
print("Average price across cities:", petrol_price.mean())
print("Difference between most and least expensive:", petrol_price.max() - petrol_price.min())

Petrol Prices: [102.5 101.8 103.2 100.9 102.1 101.5]
Cheapest city price: 100.9
Most expensive city price: 103.2
Average price across cities: 102.0
Difference between most and least expensive: 2.299999999999997


| Students | Marks |  
|----------|-------|  
| Student 1 | 85 |  
| Student 2 | 92 |  
| Student 3 | 67 |  
| Student 4 | 78 |  
| Student 5 | 88 |  
| Student 6 | 54 |  
| Student 7 | 96 |  
| Student 8 | 73 |  

Write a program using NumPy to:

Store all the marks in a NumPy array
Print the total number of students

Print the class topper's score (highest marks)

Print the lowest score (lowest marks)

Print the class average marks

Print how many students scored above 80[boolean indexing]

Print the actual marks of those who scored above 80

In [ ]:
import numpy as np

math_marks = np.array([85, 92, 67, 78, 88, 54, 96, 73])

print("All marks:", math_marks)
print("Total students:", len(math_marks))
print("Class topper score:", math_marks.max())
print("Lowest score:", math_marks.min())
print("Class average:", math_marks.mean())
print( np.sum(math_marks > 80))#np.sum() counts how many True values there are.
#True = 1, False = 0. So it adds up the 1s.
#This uses those True/False values as a filter.
#Only keep the numbers where True appeared.
#Result: [85, 92, 88, 96]
#math_marks[math_marks > 80]
print("Marks above 80:", math_marks[math_marks > 80])

All marks: [85 92 67 78 88 54 96 73]
Total students: 8
Class topper score: 96
Lowest score: 54
Class average: 79.125
How many scored above 80: 4
Marks above 80: [85 92 88 96]


| Month | Rainfall (mm) |  
|-------|--------------|  
| Jan | 6 |  
| Feb | 10 |  
| Mar | 14 |  
| Apr | 27 |  
| May | 58 |  
| Jun | 130 |  
| Jul | 180 |  
| Aug | 165 |  
| Sep | 120 |  
| Oct | 80 |  
| Nov | 35 |  
| Dec | 12 |  

Write a program using NumPy to:

Store the rainfall data in a NumPy array

Print the wettest month's rainfall (highest)

Print the driest month's rainfall (lowest)

Print the annual total rainfall

Print how many months received heavy rainfall (above 100 mm)

Print the total rainfall for the first 6 months (Jan to Jun)

Print the total rainfall for the last 6 months (Jul to Dec)

In [ ]:
rainfall_mm = np.array([6, 10, 14, 27, 58, 130, 180, 165, 120, 80, 35, 12])
months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]

print("Rainfall data:", rainfall_mm)
print("Wettest month rainfall:", rainfall_mm.max())
print("Driest month rainfall:", rainfall_mm.min())
print("Annual total rainfall:", rainfall_mm.sum())
print("Months with heavy rain (above 100mm):", np.sum(rainfall_mm > 100))
print("First 6 months total:", rainfall_mm[:6].sum())
print("Last 6 months total:", rainfall_mm[6:].sum())

Rainfall data: [  6  10  14  27  58 130 180 165 120  80  35  12]
Wettest month rainfall: 180
Driest month rainfall: 6
Annual total rainfall: 837
Months with heavy rain (above 100mm): 4
First 6 months total: 245
Last 6 months total: 592


| Month | Units Consumed |  
|-------|---------------|  
| Month 1 | 210 |  
| Month 2 | 195 |  
| Month 3 | 220 |  
| Month 4 | 240 |  
| Month 5 | 280 |  
| Month 6 | 310 |  
| Month 7 | 350 |  
| Month 8 | 340 |  
| Month 9 | 295 |  
| Month 10 | 260 |  
| Month 11 | 230 |  
| Month 12 | 200 |  

Write a program using NumPy to:

Store the monthly consumption in a NumPy array

Print the highest consumption month (in units)

Print the lowest consumption month (in units)

Print the average monthly consumption

Print the total annual consumption

Calculate the monthly bill assuming ₹5 per unit — store it in a new array[vectorized operation]

Print the monthly bills for all 12 months

Print the total annual electricity bill (in ₹)

In [ ]:
import numpy as np

electricity = np.array([210, 195, 220, 240, 280, 310, 350, 340, 295, 260, 230, 200])

print("Monthly consumption:", electricity)
print("Highest consumption month (units):", electricity.max())
print("Lowest consumption month (units):", electricity.min())
print("Average monthly consumption:", electricity.mean())
print("Total annual consumption:", electricity.sum())

rate_per_unit = 5
monthly_bills = electricity * rate_per_unit
print("Monthly bills (Rs):", monthly_bills)
print("Annual electricity bill (Rs):", monthly_bills.sum())

Monthly consumption: [210 195 220 240 280 310 350 340 295 260 230 200]
Highest consumption month (units): 350
Lowest consumption month (units): 195
Average monthly consumption: 260.8333333333333
Total annual consumption: 3130
Monthly bills (Rs): [1050  975 1100 1200 1400 1550 1750 1700 1475 1300 1150 1000]
Annual electricity bill (Rs): 15650


lets explain importance of zero on board,container first and then fill later

Why ones instead of zeros?

When you multiply any number by 1, it stays the same.
When you add 0 to any number, it stays the same.

These are called identity elements.
0 is the identity element for addition.
1 is the identity element for multiplication.

In mathematics, starting with ones is useful when:
- You are tracking multipliers (no change = 1, double = 2, half = 0.5)
- You are creating a baseline where everything starts equally weighted
- You are building a mask where everything is initially included

Example:
You give all 40 students equal weight = 1 in a voting system.
Later you might change some weights based on performance.
Starting point = all ones.text*

In [ ]:
import numpy as np


player_scores = np.zeros(11)
print("Scoreboard at start of match:", player_scores)
print("Data type:", player_scores.dtype)


player_scores[0] = 45   # opener scored 45
player_scores[1] = 82   # number 2 scored 82
player_scores[2] = 23   # number 3 scored 23
print("Scoreboard after 3 batsmen:", player_scores)
print("Team total so far:", player_scores.sum())

Scoreboard at start of match: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Data type: float64
Scoreboard after 3 batsmen: [45. 82. 23.  0.  0.  0.  0.  0.  0.  0.  0.]
Team total so far: 150.0


2.A class has 30 students. At the start of the day, all students are marked absent (0). Throughout the day, some students arrive and are marked present (1).

Roll numbers that arrived: 1, 2, 4, 6, 7, 9, 11, 13, 16, 19, 21, 23, 26, 29

(Note: In Python, array indexing starts from 0, so roll number 1 is at index 0, roll number 2 is at index 1, and so on.)
Write a program using NumPy to:

Create an array of 30 elements, all initialized to 0 (absent) using np.zeros()

Print the attendance at the start

Print how many students are present initially

Mark the arrived students as 1 (present) by updating the array

Print the attendance after marking

Print the total number of students present

Print the total number of students absent

Hint: Use np.zeros(30, dtype=int) to create the array, then update specific indices using attendance[roll_numbers_list] = 1

In [ ]:
import numpy as np

# 30 students — 0 means absent, 1 means present
# absent (0)
attendance = np.zeros(30, dtype=int)
print("Attendance at start:", attendance)
print("Total present initially:", attendance.sum())

# present
present_students = [0, 1, 3, 5, 6, 8, 10, 12, 15, 18, 20, 22, 25, 28]
attendance[present_students] = 1
print("Attendance after marking:", attendance)
print("Total present:", attendance.sum())
print("Total absent:", 30 - attendance.sum())

Attendance at start: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Total present initially: 0
Attendance after marking: [1 1 0 1 0 1 1 0 1 0 1 0 1 0 0 1 0 0 1 0 1 0 1 0 0 1 0 0 1 0]
Total present: 14
Total absent: 16


In [ ]:
import numpy as np

# 12 months of sales targets — not yet filled
# At start of year, actual sales are zero
monthly_actual_sales = np.zeros(12)
monthly_targets = np.array([50000, 55000, 60000, 65000, 70000, 75000,
                             80000, 75000, 70000, 65000, 60000, 55000])

print("Actual sales (year start):", monthly_actual_sales)
print("Targets set:", monthly_targets)

# After Q1 (3 months), fill actual sales
monthly_actual_sales[0] = 48000
monthly_actual_sales[1] = 57000
monthly_actual_sales[2] = 62000

print("After Q1 actuals:", monthly_actual_sales)
print("Q1 target vs actual:", monthly_targets[:3].sum(), "vs", monthly_actual_sales[:3].sum())

Actual sales (year start): [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Targets set: [50000 55000 60000 65000 70000 75000 80000 75000 70000 65000 60000 55000]
After Q1 actuals: [48000. 57000. 62000.     0.     0.     0.     0.     0.     0.     0.
     0.     0.]
Q1 target vs actual: 165000 vs 167000.0


In [ ]:
import numpy as np

# Status: 0 = pending review, 1 = approved, -1 = rejected
# All start as pending (zero)
loan_status = np.zeros(20, dtype=int)
print("All applications pending:", loan_status)

# After review, update some
approved = [0, 2, 4, 7, 9, 11, 14, 17]
rejected = [1, 5, 8, 13, 19]

loan_status[approved] = 1
loan_status[rejected] = -1

print("After review:", loan_status)
print("Total approved:", np.sum(loan_status == 1))
print("Total rejected:", np.sum(loan_status == -1))
print("Still pending:", np.sum(loan_status == 0))

All applications pending: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
After review: [ 1 -1  1  0  1 -1  0  1 -1  1  0  1  0 -1  1  0  0  1  0 -1]
Total approved: 8
Total rejected: 5
Still pending: 7


In [ ]:

# 5 students, 4 subjects — marks not yet entered
# Create a 5x4 matrix of zeros (2D array of zeros)
marks_matrix = np.zeros((5, 4), dtype=int)
print("Empty marks matrix:")
print(marks_matrix)
print("Shape:", marks_matrix.shape)
print("Total entries to fill:", marks_matrix.size)

Empty marks matrix:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Shape: (5, 4)
Total entries to fill: 20


Why ones instead of zeros?

When you multiply any number by 1, it stays the same.
When you add 0 to any number, it stays the same.

These are called identity elements.
0 is the identity element for addition.
1 is the identity element for multiplication.

In mathematics, starting with ones is useful when:
- You are tracking multipliers (no change = 1, double = 2, half = 0.5)
- You are creating a baseline where everything starts equally weighted
- You are building a mask where everything is initially included

Example:
You give all 40 students equal weight = 1 in a voting system.
Later you might change some weights based on performance.
Starting point = all ones.

example-1: Equal Weight for all students

In [ ]:
import numpy as np

student_weights = np.ones(40)
print("Initial weights:", student_weights)
print("Sum of all weights:", student_weights.sum())
print("This means each student contributes:", 1/40*100, "percent")

Initial weights: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Sum of all weights: 40.0
This means each student contributes: 2.5 percent


example-2:Interest Multiplier Starting Point

In [ ]:
import numpy as np

# 12 months of bank interest calculation
# Multiplier starts at 1 (no interest yet applied)
monthly_multiplier = np.ones(12)
print("Base multipliers:", monthly_multiplier)

# Apply 8% annual interest = 0.08/12 per month added
monthly_rate = 0.08 / 12
monthly_multiplier = 1 + monthly_rate
print("Monthly interest multiplier:", monthly_multiplier)

# Starting deposit of Rs 10000
deposit = 10000

# Calculate balance each month using ones as starting structure
balances = np.ones(12) * deposit
for i in range(1, 12):
    balances[i] = balances[i-1] * (1 + monthly_rate)

print("Monthly balances:")
for i, bal in enumerate(balances):
    print(f"Month {i+1}: Rs {bal:.2f}")

Base multipliers: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Monthly interest multiplier: 1.0066666666666666
Monthly balances:
Month 1: Rs 10000.00
Month 2: Rs 10066.67
Month 3: Rs 10133.78
Month 4: Rs 10201.34
Month 5: Rs 10269.35
Month 6: Rs 10337.81
Month 7: Rs 10406.73
Month 8: Rs 10476.10
Month 9: Rs 10545.95
Month 10: Rs 10616.25
Month 11: Rs 10687.03
Month 12: Rs 10758.27


Example 3 — Exam Present/Absent Default

In [ ]:
import numpy as np

# 50 students — assume everyone present by default
# 1 = present, later mark absentees as 0
attendance = np.ones(50, dtype=int)
print("Default attendance (all present):", attendance[:10], "...")
print("Total assumed present:", attendance.sum())

# Mark 5 students absent
absent_students = [3, 7, 15, 28, 42]
attendance[absent_students] = 0
print("After marking absentees:", attendance.sum(), "students present")
print("Absent count:", 50 - attendance.sum())

Default attendance (all present): [1 1 1 1 1 1 1 1 1 1] ...
Total assumed present: 50
After marking absentees: 45 students present
Absent count: 5


Example 4 — Product Rating Baseline

In [ ]:
import numpy as np

# 8 products on an e-commerce platform
# Rating starts at 1 star (default minimum)
product_ratings = np.ones(8)
product_names = ["Mobile", "Laptop", "Earphones", "Watch",
                 "Tablet", "Camera", "Speaker", "Keyboard"]

print("Default ratings:", product_ratings)

# After first week of customer reviews
actual_ratings = np.array([4.2, 3.8, 4.5, 3.2, 4.1, 3.9, 4.4, 3.7])
print("Actual ratings after reviews:", actual_ratings)
print("Average rating:", actual_ratings.mean().round(2))
print("Products rated above 4:", product_names[actual_ratings > 4])

Default ratings: [1. 1. 1. 1. 1. 1. 1. 1.]
Actual ratings after reviews: [4.2 3.8 4.5 3.2 4.1 3.9 4.4 3.7]
Average rating: 3.98


TypeError: only integer scalar arrays can be converted to a scalar index

In [ ]:
product_names = np.array(["Mobile", "Laptop", "Earphones", "Watch",
                           "Tablet", "Camera", "Speaker", "Keyboard"])
print("Products rated above 4:", product_names[actual_ratings > 4])

Example 5 — GST Rate Baseline

In [ ]:
import numpy as np

# 10 products — base GST multiplier
# Before GST: multiplier = 1 (price unchanged)
# After applying 18% GST: multiplier = 1.18
base_prices = np.array([500, 1200, 350, 2500, 180, 890, 3200, 750, 420, 1100])
print("Base prices:", base_prices)

# All products start with multiplier of 1
gst_multiplier = np.ones(10)

# Some products have 18% GST, some have 5%, some are exempt
gst_18_products = [0, 1, 4, 7]    # indices of products with 18% GST
gst_5_products = [2, 3, 5, 8]     # indices of products with 5% GST
# remaining [6, 9] are exempt — multiplier stays 1

gst_multiplier[gst_18_products] = 1.18
gst_multiplier[gst_5_products] = 1.05

print("GST multipliers:", gst_multiplier)
final_prices = base_prices * gst_multiplier
print("Final prices after GST:", final_prices.round(2))

Where do random numbers come from in computers?

Computers are deterministic machines.
They always do exactly what you tell them.
They cannot actually be random.

Instead they use a formula called a pseudo-random number generator.
You give it a starting number called a SEED.
The formula produces a sequence that LOOKS random but is predictable.

Why does this matter?
If you run the same code with the same seed, you get the same random numbers.
This is useful for:
- Research: others can reproduce your exact results
- Testing: your program gives same output every time for verification
- Debugging: you can recreate the exact situation that caused an error

Three types of random in NumPy:

1. np.random.rand()    → decimals between 0.0 and 1.0
2. np.random.randint() → whole numbers in a range you specify
3. np.random.randn()   → follows normal distribution (bell curve)
                         most values near 0, fewer far from 0

For most practical work with marks, prices, ages: use randint()
For probability and statistics work: use rand() and randn()

*
           *  *  *
        *  *  *  *  *
     *  *  *  *  *  *  *
  *  *  *  *  *  *  *  *  *
 -3  -2  -1   0   1   2   3

Most values fall in the middle.
Very few values are far from zero.
This is how most natural measurements behave.
(Height, weight, exam marks of a large class.)

Program d — Random Numbers in ndarray
Example 1 — Simulated Exam Marks

In [ ]:
import numpy as np

np.random.seed(42)   # set seed for reproducibility

# Simulate marks of 30 students in a maths exam (out of 100)
marks = np.random.randint(40, 101, size=30)
# randint(low, high, size) → low is included, high is EXCLUDED
# So randint(40, 101) gives numbers from 40 to 100

print("Simulated class marks:")
print(marks)
print()
print("Highest mark:", marks.max())
print("Lowest mark:", marks.min())
print("Class average:", marks.mean().round(2))
print("Students above 75:", np.sum(marks > 75))
print("Students below 50:", np.sum(marks < 50))

Simulated class marks:
[ 78  91  68  54  82  47 100  60  78  97  58  62  50  50  63  92  75  79
  63  42  61  92  41  63  83  69  77  41  99  60]

Highest mark: 100
Lowest mark: 41
Class average: 69.17
Students above 75: 12
Students below 50: 4


Example 2 — Simulated Daily Temperatures

In [ ]:
import numpy as np

np.random.seed(10)

# Simulate temperatures in Vizag for 30 days (in Celsius)
# Vizag temperature range roughly 25 to 38 degrees in summer
temperatures = np.random.randint(25, 39, size=30)

print("30 days of simulated temperatures (°C):")
print(temperatures)
print()
print("Hottest day:", temperatures.max(), "°C")
print("Coolest day:", temperatures.min(), "°C")
print("Monthly average:", temperatures.mean().round(1), "°C")
print("Days above 35°C:", np.sum(temperatures > 35))
print("Days below 28°C:", np.sum(temperatures < 28))

30 days of simulated temperatures (°C):
[34 38 29 25 26 36 37 34 38 25 38 26 35 33 34 25 35 33 31 29 28 25 29 36
 31 33 36 35 26 33]

Hottest day: 38 °C
Coolest day: 25 °C
Monthly average: 31.8 °C
Days above 35°C: 7
Days below 28°C: 7


Example 3 — Simulated Loan Amounts

In [ ]:
import numpy as np

np.random.seed(7)

# Simulate 50 loan applications
# Loan amounts between Rs 50,000 and Rs 5,00,000
loan_amounts = np.random.randint(50000, 500001, size=50)

print("Sample of first 10 loan amounts:")
print(loan_amounts[:10])
print()
print("Smallest loan:", loan_amounts.min())
print("Largest loan:", loan_amounts.max())
print("Average loan amount:", loan_amounts.mean().round(2))
print("Loans above 3 lakhs:", np.sum(loan_amounts > 300000))
print("Loans below 1 lakh:", np.sum(loan_amounts < 100000))

# What percentage are large loans?
large_loan_pct = np.sum(loan_amounts > 300000) / len(loan_amounts) * 100
print("Percentage of large loans:", large_loan_pct.round(1), "%")

Sample of first 10 loan amounts:
[111615 239636  99689  60742 285075 365603 378599 129463 411820 176137]

Smallest loan: 60742
Largest loan: 490521
Average loan amount: 251169.56
Loans above 3 lakhs: 19
Loans below 1 lakh: 9
Percentage of large loans: 38.0 %


Example 4 — Simulated Product Ratings (Decimals)

In [ ]:
import numpy as np

np.random.seed(25)

# 100 customer ratings for a product (between 1.0 and 5.0)
# Using rand() which gives 0 to 1, then scale it
ratings = np.random.rand(100) * 4 + 1
# rand(100) gives 100 numbers between 0.0 and 1.0
# multiply by 4 → range becomes 0.0 to 4.0
# add 1      → range becomes 1.0 to 5.0

print("First 10 ratings:", ratings[:10].round(2))
print()
print("Average rating:", ratings.mean().round(2))
print("Ratings above 4.0:", np.sum(ratings > 4.0))
print("Ratings below 2.0:", np.sum(ratings < 2.0))
print("Percentage 5-star range (above 4.5):",
      (np.sum(ratings > 4.5) / 100 * 100).round(1), "%")

First 10 ratings: [4.48 3.33 2.12 1.74 2.64 1.47 3.74 2.75 3.22 2.47]

Average rating: 2.96
Ratings above 4.0: 21
Ratings below 2.0: 22
Percentage 5-star range (above 4.5): 7.0 %


Example 5 — Normal Distribution of Heights

In [ ]:
import numpy as np

np.random.seed(33)

# Simulate heights of 200 students in cm
# Average Indian male height ~165 cm, std dev ~7 cm
heights = np.random.randn(200) * 7 + 165
# randn(200) gives 200 numbers following normal distribution
# multiply by 7  → spread becomes 7 (standard deviation)
# add 165        → center shifts to 165 (mean)

print("First 10 simulated heights:", heights[:10].round(1))
print()
print("Average height:", heights.mean().round(1), "cm")
print("Tallest student:", heights.max().round(1), "cm")
print("Shortest student:", heights.min().round(1), "cm")
print("Students above 175 cm:", np.sum(heights > 175))
print("Students below 155 cm:", np.sum(heights < 155))

First 10 simulated heights: [162.8 153.8 154.3 161.  163.5 166.8 164.  179.1 164.3 168. ]

Average height: 164.4 cm
Tallest student: 184.7 cm
Shortest student: 145.3 cm
Students above 175 cm: 16
Students below 155 cm: 20


Program e — Array of Your Choice
The Philosophy Behind This Exercise

Program f — Identity Matrix in NumPy

Example 1 — Basic Identity Matrix

In [ ]:
import numpy as np

# Create 4x4 identity matrix
I4 = np.eye(4)
print("4×4 Identity Matrix:")
print(I4)
print()
print("Shape:", I4.shape)
print("Data type:", I4.dtype)
print("Sum of diagonal (should be 4):", np.trace(I4))
print("Sum of all elements:", I4.sum())

4×4 Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Shape: (4, 4)
Data type: float64
Sum of diagonal (should be 4): 4.0
Sum of all elements: 4.0


Example 2 — Verifying Identity Property

In [ ]:
import numpy as np

# Take any matrix (student marks: 3 students, 3 subjects)
A = np.array([[85, 92, 78],
              [70, 65, 90],
              [95, 88, 76]])

I3 = np.eye(3)

# Multiply A × I — should give A back
result = np.dot(A, I3)
print("Original matrix A:")
print(A)
print()
print("A × Identity:")
print(result)
print()
print("Are they equal?", np.array_equal(A, result))

Original matrix A:
[[85 92 78]
 [70 65 90]
 [95 88 76]]

A × Identity:
[[85. 92. 78.]
 [70. 65. 90.]
 [95. 88. 76.]]

Are they equal? True


Example 3 — Identity in Integer Form

In [ ]:
import numpy as np

# Identity matrix with integer data type
I5 = np.eye(5, dtype=int)
print("5×5 Identity Matrix (integer type):")
print(I5)
print()

# Create a custom diagonal matrix using identity
# Multiply identity by a vector to make diagonal matrix
weights = np.array([0.2, 0.3, 0.25, 0.15, 0.1])
# Multiply each row by corresponding weight
W = np.eye(5) * weights
print("Weighted diagonal matrix:")
print(W)
print("This represents: 5 different subjects with different weightages")

5×5 Identity Matrix (integer type):
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]

Weighted diagonal matrix:
[[0.2  0.   0.   0.   0.  ]
 [0.   0.3  0.   0.   0.  ]
 [0.   0.   0.25 0.   0.  ]
 [0.   0.   0.   0.15 0.  ]
 [0.   0.   0.   0.   0.1 ]]
This represents: 5 different subjects with different weightages


Example 4 — Off-Diagonal Identity (Shifted)

In [ ]:
import numpy as np

# np.eye() can also create matrices with 1s off the main diagonal
# k=0 is default (main diagonal)
# k=1 means one above main diagonal
# k=-1 means one below main diagonal

main_diag = np.eye(4, k=0)
above_diag = np.eye(4, k=1)
below_diag = np.eye(4, k=-1)

print("Main diagonal:")
print(main_diag)
print("One above main diagonal:")
print(above_diag)
print("One below main diagonal:")
print(below_diag)

Main diagonal:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
One above main diagonal:
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
One below main diagonal:
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


Example 5 — Non-Square Identity-Like Matrix
python

In [ ]:
import numpy as np

# np.eye() can create non-square matrices too
# 3 rows, 5 columns with 1s on diagonal
rect_identity = np.eye(3, 5)
print("3×5 matrix with 1s on diagonal:")
print(rect_identity)
print()

# Practical example: selecting specific columns from a dataset
# This is called a selection matrix in linear algebra
print("Shape:", rect_identity.shape)
print("This selects first 3 columns from a 5-column matrix when multiplied")

3×5 matrix with 1s on diagonal:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]

Shape: (3, 5)
This selects first 3 columns from a 5-column matrix when multiplied


Program g — Evenly Spaced ndarray

Example 1 — Roll Numbers for a Class

In [ ]:
import numpy as np

# Roll numbers for a class of 60 students
roll_numbers = np.arange(1, 61)
print("All roll numbers:")
print(roll_numbers)
print()

# Every 5th student (for sampling)
every_5th = np.arange(5, 61, 5)
print("Every 5th roll number:", every_5th)

# Roll numbers from Section B (starting from 101)
section_b = np.arange(101, 161)
print("Section B roll numbers start:", section_b[:5], "... end:", section_b[-5:])

All roll numbers:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]

Every 5th roll number: [ 5 10 15 20 25 30 35 40 45 50 55 60]
Section B roll numbers start: [101 102 103 104 105] ... end: [156 157 158 159 160]


Example 2 — Temperature Scale Conversion Table

In [ ]:
import numpy as np

# Create Celsius temperatures from 0 to 100 in steps of 5
celsius = np.arange(0, 101, 5)

# Convert to Fahrenheit
fahrenheit = (celsius * 9/5) + 32

print("Temperature Conversion Table:")
print("Celsius | Fahrenheit")
print("-" * 25)
for c, f in zip(celsius, fahrenheit):
    print(f"  {c:3}°C  |  {f:6.1f}°F")

Temperature Conversion Table:
Celsius | Fahrenheit
-------------------------
    0°C  |    32.0°F
    5°C  |    41.0°F
   10°C  |    50.0°F
   15°C  |    59.0°F
   20°C  |    68.0°F
   25°C  |    77.0°F
   30°C  |    86.0°F
   35°C  |    95.0°F
   40°C  |   104.0°F
   45°C  |   113.0°F
   50°C  |   122.0°F
   55°C  |   131.0°F
   60°C  |   140.0°F
   65°C  |   149.0°F
   70°C  |   158.0°F
   75°C  |   167.0°F
   80°C  |   176.0°F
   85°C  |   185.0°F
   90°C  |   194.0°F
   95°C  |   203.0°F
  100°C  |   212.0°F


Example 3 — Monthly EMI Schedule

In [ ]:
import numpy as np

# Loan of Rs 1,00,000 to be repaid in 12 months
# Create month numbers
months = np.arange(1, 13)
emi = 9000   # monthly EMI in rupees

# Calculate outstanding balance each month
principal = 100000
outstanding = principal - (emi * months)
outstanding = np.maximum(outstanding, 0)  # cannot go below 0

print("EMI Repayment Schedule:")
print("Month | EMI Paid | Outstanding Balance")
print("-" * 45)
for m, bal in zip(months, outstanding):
    total_paid = m * emi
    print(f"  {m:2}   |  {emi:6}   |  Rs {bal:8,}")

EMI Repayment Schedule:
Month | EMI Paid | Outstanding Balance
---------------------------------------------
   1   |    9000   |  Rs   91,000
   2   |    9000   |  Rs   82,000
   3   |    9000   |  Rs   73,000
   4   |    9000   |  Rs   64,000
   5   |    9000   |  Rs   55,000
   6   |    9000   |  Rs   46,000
   7   |    9000   |  Rs   37,000
   8   |    9000   |  Rs   28,000
   9   |    9000   |  Rs   19,000
  10   |    9000   |  Rs   10,000
  11   |    9000   |  Rs    1,000
  12   |    9000   |  Rs        0


Example 4 — Linspace for Graph Points

In [ ]:
import numpy as np

# Create 100 evenly spaced points between 0 and 2π for a sine wave
# (Preview of matplotlib — will be used in Week 12)
x_points = np.linspace(0, 6.28, 100)   # 0 to 2π
print("First 5 x-points:", x_points[:5].round(3))
print("Last 5 x-points:", x_points[-5:].round(3))
print("Total points:", len(x_points))
print("Step size:", (x_points[1] - x_points[0]).round(4))

# Apply sine function to all points simultaneously
y_points = np.sin(x_points)
print("First 5 sine values:", y_points[:5].round(3))
print("Maximum of sine:", y_points.max().round(4))
print("Minimum of sine:", y_points.min().round(4))

First 5 x-points: [0.    0.063 0.127 0.19  0.254]
Last 5 x-points: [6.026 6.09  6.153 6.217 6.28 ]
Total points: 100
Step size: 0.0634
First 5 sine values: [0.    0.063 0.127 0.189 0.251]
Maximum of sine: 0.9999
Minimum of sine: -0.9998


Example 5 — Percentage Marks Thresholds

In [ ]:
import numpy as np

# Create grade boundaries from 0 to 100 in steps of 10
grade_boundaries = np.arange(0, 101, 10)
print("Grade boundaries:", grade_boundaries)

# Use linspace to create fine-grained percentage scale
fine_scale = np.linspace(0, 100, 11)
print("Linspace (same but using linspace):", fine_scale)

# Simulate 40 student marks
np.random.seed(5)
student_marks = np.random.randint(35, 100, size=40)

# Count how many students fall in each grade band
print("\nGrade Distribution:")
grade_labels = ["F(0-39)", "D(40-49)", "C(50-59)",
                "B(60-69)", "B+(70-79)", "A(80-89)", "A+(90-100)"]
boundaries = [0, 40, 50, 60, 70, 80, 90, 101]

for i in range(len(grade_labels)):
    low = boundaries[i]
    high = boundaries[i+1]
    count = np.sum((student_marks >= low) & (student_marks < high))
    print(f"  {grade_labels[i]}: {count} students")

Grade boundaries: [  0  10  20  30  40  50  60  70  80  90 100]
Linspace (same but using linspace): [  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]

Grade Distribution:
  F(0-39): 5 students
  D(40-49): 6 students
  C(50-59): 6 students
  B(60-69): 10 students
  B+(70-79): 4 students
  A(80-89): 3 students
  A+(90-100): 6 students


**WEEK 2 — Shape and Reshaping of NumPy Arrays**

Example 1 — SENSEX Values (1D)

In [ ]:
import numpy as np

sensex_week = np.array([60120, 59890, 61340, 60780, 62100])
print("SENSEX data:", sensex_week)
print("Number of dimensions:", sensex_week.ndim)
print("This is a 1D array — one direction — only position along the list matters")

SENSEX data: [60120 59890 61340 60780 62100]
Number of dimensions: 1
This is a 1D array — one direction — only position along the list matters


Example 2 — Student Marks Table (2D)


In [ ]:
import numpy as np

# 4 students, 5 subjects
marks = np.array([[85, 92, 78, 88, 76],
                  [70, 65, 90, 82, 79],
                  [95, 88, 76, 91, 84],
                  [60, 72, 68, 75, 80]])

print("Marks table:")
print(marks)
print()
print("Number of dimensions:", marks.ndim)
print("This is 2D — two directions — row (which student) AND column (which subject)")
print("To find one value I need two coordinates: marks[student_index, subject_index]")
print("Marks of student 2 in subject 3:", marks[1, 2])

Marks table:
[[85 92 78 88 76]
 [70 65 90 82 79]
 [95 88 76 91 84]
 [60 72 68 75 80]]

Number of dimensions: 2
This is 2D — two directions — row (which student) AND column (which subject)
To find one value I need two coordinates: marks[student_index, subject_index]
Marks of student 2 in subject 3: 90


Example 3 — Monthly Sales Data (3D)

In [ ]:
import numpy as np

# 3 years × 4 quarters × 3 months = 3D array
# Values represent sales in lakhs
sales_data = np.array([
    [[12, 15, 18], [22, 19, 25], [30, 28, 32], [20, 18, 22]],   # Year 1
    [[14, 17, 20], [24, 21, 27], [33, 31, 35], [22, 20, 24]],   # Year 2
    [[16, 19, 22], [26, 23, 29], [36, 34, 38], [24, 22, 26]]    # Year 3
])

print("Sales data shape:", sales_data.shape)
print("Number of dimensions:", sales_data.ndim)
print()
print("To find a specific value I need 3 coordinates:")
print("Year 2, Quarter 3, Month 1 sales:", sales_data[1, 2, 0], "lakhs")
print()
print("Year 2 data:")
print(sales_data[1])
print("Year 2, Quarter 3 data:", sales_data[1, 2])

Sales data shape: (3, 4, 3)
Number of dimensions: 3

To find a specific value I need 3 coordinates:
Year 2, Quarter 3, Month 1 sales: 33 lakhs

Year 2 data:
[[14 17 20]
 [24 21 27]
 [33 31 35]
 [22 20 24]]
Year 2, Quarter 3 data: [33 31 35]


Example 4 — Comparing ndim Across Different Arrays

In [ ]:
import numpy as np

# Create arrays of different dimensions
a_0d = np.array(42)                              # 0D — scalar
a_1d = np.array([1, 2, 3, 4, 5])               # 1D — vector
a_2d = np.array([[1, 2, 3], [4, 5, 6]])         # 2D — matrix
a_3d = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])              # 3D — cube

print("Scalar (0D):", a_0d, "→ ndim:", a_0d.ndim)
print("Vector (1D):", a_1d, "→ ndim:", a_1d.ndim)
print("Matrix (2D):")
print(a_2d)
print("ndim:", a_2d.ndim)
print("Cube (3D):")
print(a_3d)
print("ndim:", a_3d.ndim)

Scalar (0D): 42 → ndim: 0
Vector (1D): [1 2 3 4 5] → ndim: 1
Matrix (2D):
[[1 2 3]
 [4 5 6]]
ndim: 2
Cube (3D):
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
ndim: 3


Example 5 — IPL Season Statistics (Verify Understanding)

In [ ]:
import numpy as np

# Team batting scores across matches — 2D: teams × matches
ipl_scores = np.array([
    [182, 165, 203, 178, 156],   # CSK
    [175, 190, 168, 195, 180],   # MI
    [160, 172, 185, 177, 163],   # RCB
    [188, 175, 192, 183, 170]    # KKR
])

teams = ["CSK", "MI ", "RCB", "KKR"]

print("IPL Scores (teams × matches):")
print(ipl_scores)
print()
print("Dimensions:", ipl_scores.ndim, "(2D: teams in rows, matches in columns)")
print()
print("Team averages:")
for i, team in enumerate(teams):
    avg = ipl_scores[i].mean()
    print(f"  {team}: {avg:.1f} runs per match")

print()
print("Best score of tournament:", ipl_scores.max())
print("Match with best score: Team", np.where(ipl_scores == ipl_scores.max())[0][0],
      "Match", np.where(ipl_scores == ipl_scores.max())[1][0])

IPL Scores (teams × matches):
[[182 165 203 178 156]
 [175 190 168 195 180]
 [160 172 185 177 163]
 [188 175 192 183 170]]

Dimensions: 2 (2D: teams in rows, matches in columns)

Team averages:
  CSK: 176.8 runs per match
  MI : 181.6 runs per match
  RCB: 171.4 runs per match
  KKR: 181.6 runs per match

Best score of tournament: 203
Match with best score: Team 0 Match 2


Program b — Shape of a NumPy Array

Example 1 — Student Marks Shape

In [ ]:
import numpy as np

# Marks of 5 students in 6 subjects
marks = np.array([
    [85, 92, 78, 88, 76, 90],
    [70, 65, 90, 82, 79, 85],
    [95, 88, 76, 91, 84, 92],
    [60, 72, 68, 75, 80, 78],
    [88, 79, 85, 83, 77, 94]
])

print("Marks array:")
print(marks)
print()
print("Shape:", marks.shape)
print("Number of students:", marks.shape[0])
print("Number of subjects:", marks.shape[1])
print()
print("Reading shape:", marks.shape[0], "students, each with",
      marks.shape[1], "subject marks")

Marks array:
[[85 92 78 88 76 90]
 [70 65 90 82 79 85]
 [95 88 76 91 84 92]
 [60 72 68 75 80 78]
 [88 79 85 83 77 94]]

Shape: (5, 6)
Number of students: 5
Number of subjects: 6

Reading shape: 5 students, each with 6 subject marks


Example 2 — Loan Dataset Shape

In [ ]:
import numpy as np
np.random.seed(15)

# Simulate a small loan dataset
# 50 applications, 6 features each
# Features: [income, loan_amount, tenure, credit_score, age, existing_loans]
loan_data = np.column_stack([
    np.random.randint(20000, 150000, 50),    # income
    np.random.randint(50000, 500000, 50),    # loan amount
    np.random.randint(12, 60, 50),           # tenure in months
    np.random.randint(600, 850, 50),         # credit score
    np.random.randint(22, 60, 50),           # age
    np.random.randint(0, 4, 50)              # existing loans
])

print("Loan dataset shape:", loan_data.shape)
print("Number of applications:", loan_data.shape[0])
print("Number of features per application:", loan_data.shape[1])
print()
print("First 3 applications:")
print(loan_data[:3])
print()
print("Feature means:")
feature_names = ["Income", "Loan Amount", "Tenure", "Credit Score", "Age", "Existing Loans"]
for i, name in enumerate(feature_names):
    print(f"  {name}: {loan_data[:, i].mean():.1f}")

Loan dataset shape: (50, 6)
Number of applications: 50
Number of features per application: 6

First 3 applications:
[[ 27624 445682     17    668     56      2]
 [ 72981 357734     12    741     26      2]
 [ 28076  72632     21    831     24      3]]

Feature means:
  Income: 81654.6
  Loan Amount: 274200.9
  Tenure: 37.5
  Credit Score: 717.8
  Age: 39.1
  Existing Loans: 1.7


Example 3 — IPL 3D Data Shape

In [ ]:
import numpy as np

# 4 years × 8 teams × 5 matches of IPL scores
np.random.seed(20)
ipl_3d = np.random.randint(140, 210, size=(4, 8, 5))

print("IPL data shape:", ipl_3d.shape)
print("Number of years:", ipl_3d.shape[0])
print("Number of teams:", ipl_3d.shape[1])
print("Number of matches:", ipl_3d.shape[2])
print()
print("Total data points:", ipl_3d.shape[0] * ipl_3d.shape[1] * ipl_3d.shape[2])
print("Verification using size:", ipl_3d.size)
print()
print("Year 1, Team 1 scores:", ipl_3d[0, 0, :])
print("Overall average score:", ipl_3d.mean().round(1))

IPL data shape: (4, 8, 5)
Number of years: 4
Number of teams: 8
Number of matches: 5

Total data points: 160
Verification using size: 160

Year 1, Team 1 scores: [155 168 149 160 162]
Overall average score: 171.3


Example 4 — Shape Before and After Adding Data

In [ ]:
import numpy as np

# Start with marks of 3 students
batch1 = np.array([[85, 92, 78],
                   [70, 65, 90],
                   [95, 88, 76]])

print("Batch 1 shape:", batch1.shape, "→", batch1.shape[0], "students")

# Add 2 more students (stack vertically)
batch2 = np.array([[80, 75, 88],
                   [92, 85, 79]])

combined = np.vstack([batch1, batch2])
print("Batch 2 shape:", batch2.shape, "→", batch2.shape[0], "students")
print("Combined shape:", combined.shape, "→", combined.shape[0], "students total")
print()
print("Combined marks:")
print(combined)

Batch 1 shape: (3, 3) → 3 students
Batch 2 shape: (2, 3) → 2 students
Combined shape: (5, 3) → 5 students total

Combined marks:
[[85 92 78]
 [70 65 90]
 [95 88 76]
 [80 75 88]
 [92 85 79]]


Example 5 — Dynamic Shape Usage in a Function

In [ ]:
import numpy as np

def class_report(marks_array):
    rows, cols = marks_array.shape
    print(f"Class Report: {rows} students, {cols} subjects")
    print(f"Overall average: {marks_array.mean():.1f}")
    print(f"Subject averages: {marks_array.mean(axis=0).round(1)}")
    print(f"Student averages: {marks_array.mean(axis=1).round(1)}")
    print(f"Top student index: {marks_array.mean(axis=1).argmax()}")
    print(f"Hardest subject index: {marks_array.mean(axis=0).argmin()}")

marks = np.array([
    [85, 92, 78, 88],
    [70, 65, 90, 82],
    [95, 88, 76, 91],
    [60, 72, 68, 75],
    [88, 79, 85, 83]
])

class_report(marks)

Class Report: 5 students, 4 subjects
Overall average: 80.5
Subject averages: [79.6 79.2 79.4 83.8]
Student averages: [85.8 76.8 87.5 68.8 83.8]
Top student index: 2
Hardest subject index: 1


Program c — Size of a NumPy Array

Example 1 — Basic Size

In [ ]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])
b = np.array([[1, 2, 3], [4, 5, 6]])
c = np.zeros((4, 5, 6))

print("Array a — shape:", a.shape, "→ size:", a.size)
print("Array b — shape:", b.shape, "→ size:", b.size)
print("Array c — shape:", c.shape, "→ size:", c.size)
print()
print("Memory used by c:", c.nbytes, "bytes =", c.nbytes/1024, "KB")

Array a — shape: (5,) → size: 5
Array b — shape: (2, 3) → size: 6
Array c — shape: (4, 5, 6) → size: 120

Memory used by c: 960 bytes = 0.9375 KB


Example 2 — Hospital Patient Records

In [ ]:
import numpy as np

# Patient records: 200 patients, 10 vital measurements each
patient_data = np.random.rand(200, 10)
print("Patient dataset:")
print("  Patients:", patient_data.shape[0])
print("  Measurements per patient:", patient_data.shape[1])
print("  Total data points:", patient_data.size)
print("  Memory used:", patient_data.nbytes, "bytes")
print()

# Subset — ICU patients (first 20)
icu_patients = patient_data[:20, :]
print("ICU subset:")
print("  Patients:", icu_patients.shape[0])
print("  Total data points:", icu_patients.size)

Patient dataset:
  Patients: 200
  Measurements per patient: 10
  Total data points: 2000
  Memory used: 16000 bytes

ICU subset:
  Patients: 20
  Total data points: 200


Example 3 — Size vs Shape vs ndim Together

In [ ]:
import numpy as np

arrays = {
    "1D vector": np.arange(24),
    "2D matrix (4x6)": np.arange(24).reshape(4, 6),
    "3D cube (2x3x4)": np.arange(24).reshape(2, 3, 4)
}

print(f"{'Array':<20} {'shape':<15} {'ndim':<8} {'size'}")
print("-" * 55)
for name, arr in arrays.items():
    print(f"{name:<20} {str(arr.shape):<15} {arr.ndim:<8} {arr.size}")

Array                shape           ndim     size
-------------------------------------------------------
1D vector            (24,)           1        24
2D matrix (4x6)      (4, 6)          2        24
3D cube (2x3x4)      (2, 3, 4)       3        24


Example 4 — Checking Size Before Operations

In [ ]:
import numpy as np

def safe_multiply(arr1, arr2):
    if arr1.size != arr2.size:
        print(f"Cannot multiply: sizes differ ({arr1.size} vs {arr2.size})")
        return None
    return arr1.flatten() * arr2.flatten()

marks = np.array([[85, 92, 78], [70, 65, 90]])       # size 6
weights = np.array([0.3, 0.4, 0.3])                   # size 3
weights2 = np.array([0.3, 0.4, 0.3, 0.2, 0.1, 0.1]) # size 6

print("marks size:", marks.size)
print("weights size:", weights.size)
print("weights2 size:", weights2.size)

result = safe_multiply(marks, weights)
print("marks × weights:", result)

result2 = safe_multiply(marks, weights2)
print("marks × weights2:", result2)

marks size: 6
weights size: 3
weights2 size: 6
Cannot multiply: sizes differ (6 vs 3)
marks × weights: None
marks × weights2: [25.5 36.8 23.4 14.   6.5  9. ]


Example 5 — Memory Comparison

In [ ]:
import numpy as np

# Compare memory: Python list vs NumPy array
import sys

python_list = list(range(10000))
numpy_array = np.arange(10000)

print("Python list of 10000 integers:")
print("  Memory:", sys.getsizeof(python_list), "bytes approx")

print("NumPy array of 10000 integers:")
print("  Memory:", numpy_array.nbytes, "bytes")
print("  Memory with metadata:", sys.getsizeof(numpy_array), "bytes")

print()
ratio = sys.getsizeof(python_list) / numpy_array.nbytes
print(f"Python list uses ~{ratio:.1f}× more memory than NumPy array")
print("This is why NumPy is used for large numerical datasets")

Python list of 10000 integers:
  Memory: 80056 bytes approx
NumPy array of 10000 integers:
  Memory: 80000 bytes
  Memory with metadata: 80112 bytes

Python list uses ~1.0× more memory than NumPy array
This is why NumPy is used for large numerical datasets


Program d — Reshaping a NumPy Array

Example 1 — Reshaping Student Marks

In [ ]:
import numpy as np

# 12 marks as a flat list (maybe received from a database)
raw_marks = np.array([85, 92, 78, 88, 70, 65, 90, 82, 95, 88, 76, 91])
print("Raw marks (1D):", raw_marks)
print("Shape:", raw_marks.shape)

# Interpret as 4 students × 3 subjects
marks_4x3 = raw_marks.reshape(4, 3)
print("\nAs 4 students, 3 subjects:")
print(marks_4x3)

# Interpret as 3 students × 4 subjects
marks_3x4 = raw_marks.reshape(3, 4)
print("\nAs 3 students, 4 subjects:")
print(marks_3x4)

# Use -1 shortcut
marks_auto = raw_marks.reshape(2, -1)  # 2 rows, NumPy figures out columns
print("\nUsing reshape(2, -1):")
print(marks_auto)
print("Shape:", marks_auto.shape)

Raw marks (1D): [85 92 78 88 70 65 90 82 95 88 76 91]
Shape: (12,)

As 4 students, 3 subjects:
[[85 92 78]
 [88 70 65]
 [90 82 95]
 [88 76 91]]

As 3 students, 4 subjects:
[[85 92 78 88]
 [70 65 90 82]
 [95 88 76 91]]

Using reshape(2, -1):
[[85 92 78 88 70 65]
 [90 82 95 88 76 91]]
Shape: (2, 6)


Example 2 — Reshaping IPL Data

In [ ]:
import numpy as np

# 24 match scores in a flat array
np.random.seed(8)
all_scores = np.random.randint(140, 210, size=24)
print("All 24 scores:", all_scores)

# Arrange as 4 teams × 6 matches
teams_matches = all_scores.reshape(4, 6)
team_names = ["CSK", "MI", "RCB", "KKR"]
print("\n4 teams × 6 matches:")
print(teams_matches)
print()
for i, team in enumerate(team_names):
    print(f"{team} average: {teams_matches[i].mean():.1f}")

All 24 scores: [207 145 148 203 188 200 189 167 153 149 201 155 199 158 154 196 149 191
 208 193 193 199 182 166]

4 teams × 6 matches:
[[207 145 148 203 188 200]
 [189 167 153 149 201 155]
 [199 158 154 196 149 191]
 [208 193 193 199 182 166]]

CSK average: 181.8
MI average: 169.0
RCB average: 174.5
KKR average: 190.2


Example 3 — Reshape for Machine Learning Input

In [ ]:
import numpy as np

# In ML, data is usually 2D: (samples, features)
# Sometimes raw data comes as 1D and needs reshaping

# 1D array: 20 temperatures (raw sensor data)
raw_temps = np.array([32, 34, 31, 35, 33, 36, 30, 29, 31, 33,
                       35, 37, 38, 36, 34, 32, 30, 28, 31, 33])

print("Raw sensor data (1D):", raw_temps)
print("Shape:", raw_temps.shape)

# ML model expects 2D input: (20 samples, 1 feature each)
ml_input = raw_temps.reshape(-1, 1)   # -1 means "figure out the rows"
print("\nML-ready shape:", ml_input.shape)
print("First 5 rows:")
print(ml_input[:5])

Raw sensor data (1D): [32 34 31 35 33 36 30 29 31 33 35 37 38 36 34 32 30 28 31 33]
Shape: (20,)

ML-ready shape: (20, 1)
First 5 rows:
[[32]
 [34]
 [31]
 [35]
 [33]]


Example 4 — 3D Reshape for Image Data Concept

In [ ]:
import numpy as np

# Imagine a grayscale image is stored as a flat array of pixel values
# For a small 4×4 image, that is 16 pixel values
pixel_values = np.arange(16) * 16  # pixel intensities 0 to 240

print("Flat pixel array:", pixel_values)
print("Shape:", pixel_values.shape)

# Reshape to 4×4 image (2D)
image_2d = pixel_values.reshape(4, 4)
print("\nAs 4×4 image:")
print(image_2d)

# For a color image (RGB), add 3 channels → 3D shape
# Simulate by tiling the pixel values across 3 channels
image_rgb = np.stack([image_2d, image_2d//2, image_2d//4], axis=2)
print("\nAs 4×4×3 RGB image (Red, Green, Blue channels):")
print("Shape:", image_rgb.shape)
print("Top-left pixel RGB values:", image_rgb[0, 0, :])

Flat pixel array: [  0  16  32  48  64  80  96 112 128 144 160 176 192 208 224 240]
Shape: (16,)

As 4×4 image:
[[  0  16  32  48]
 [ 64  80  96 112]
 [128 144 160 176]
 [192 208 224 240]]

As 4×4×3 RGB image (Red, Green, Blue channels):
Shape: (4, 4, 3)
Top-left pixel RGB values: [0 0 0]


Example 5 — Reshape Error and Fix

In [ ]:
import numpy as np

arr = np.arange(10)
print("Original array:", arr)
print("Size:", arr.size)

# Try impossible reshape
try:
    bad_reshape = arr.reshape(3, 4)  # 3×4=12 ≠ 10
    print("Reshaping to (3,4):", bad_reshape)
except ValueError as e:
    print("ERROR:", e)
    print("Cannot reshape 10 elements into (3,4) because 3×4=12 ≠ 10")

# Correct reshape
good_reshape = arr.reshape(2, 5)
print("\nCorrect reshape (2,5):", good_reshape)
print("2×5 =", 2*5, "= 10 ✓")

Original array: [0 1 2 3 4 5 6 7 8 9]
Size: 10
ERROR: cannot reshape array of size 10 into shape (3,4)
Cannot reshape 10 elements into (3,4) because 3×4=12 ≠ 10

Correct reshape (2,5): [[0 1 2 3 4]
 [5 6 7 8 9]]
2×5 = 10 = 10 ✓


Program e — Flattening a NumPy Array

Example 1 — Flatten Student Marks

In [ ]:
import numpy as np

marks = np.array([[85, 92, 78, 88],
                  [70, 65, 90, 82],
                  [95, 88, 76, 91]])

print("2D marks:")
print(marks)
print("Shape:", marks.shape)

flat_marks = marks.flatten()
print("\nFlattened marks:", flat_marks)
print("Shape:", flat_marks.shape)

print("\nNow easy to find overall statistics:")
print("Highest mark in entire class:", flat_marks.max())
print("Lowest mark in entire class:", flat_marks.min())
print("Overall class average:", flat_marks.mean().round(2))
print("Count of marks above 85:", np.sum(flat_marks > 85))

2D marks:
[[85 92 78 88]
 [70 65 90 82]
 [95 88 76 91]]
Shape: (3, 4)

Flattened marks: [85 92 78 88 70 65 90 82 95 88 76 91]
Shape: (12,)

Now easy to find overall statistics:
Highest mark in entire class: 95
Lowest mark in entire class: 65
Overall class average: 83.33
Count of marks above 85: 6


Example 2 — Flatten vs Ravel (the Difference)

In [ ]:
import numpy as np

original = np.array([[10, 20, 30],
                     [40, 50, 60]])

flat_copy = original.flatten()
ravel_view = original.ravel()

print("Original:", original.flatten())
print("Flattened copy:", flat_copy)
print("Raveled view:", ravel_view)

# Change the raveled view
ravel_view[0] = 999
print("\nAfter changing ravel_view[0] to 999:")
print("ravel_view:", ravel_view)
print("original (ALSO CHANGED because ravel shares memory):", original)

# Now try with flatten — original should NOT change
original2 = np.array([[10, 20, 30], [40, 50, 60]])
flat_copy2 = original2.flatten()
flat_copy2[0] = 999
print("\nAfter changing flat_copy2[0] to 999:")
print("flat_copy2:", flat_copy2)
print("original2 (UNCHANGED because flatten makes a copy):", original2)

Original: [10 20 30 40 50 60]
Flattened copy: [10 20 30 40 50 60]
Raveled view: [10 20 30 40 50 60]

After changing ravel_view[0] to 999:
ravel_view: [999  20  30  40  50  60]
original (ALSO CHANGED because ravel shares memory): [[999  20  30]
 [ 40  50  60]]

After changing flat_copy2[0] to 999:
flat_copy2: [999  20  30  40  50  60]
original2 (UNCHANGED because flatten makes a copy): [[10 20 30]
 [40 50 60]]


Example 3 — Flatten for Sorting All Elements Together

In [ ]:
import numpy as np

# Marks of 5 students in 4 subjects
marks = np.array([[85, 92, 78, 88],
                  [70, 65, 90, 82],
                  [95, 88, 76, 91],
                  [60, 72, 68, 75],
                  [88, 79, 85, 83]])

all_marks = marks.flatten()
sorted_marks = np.sort(all_marks)[::-1]   # sort descending

print("Top 5 marks across all students and subjects:")
print(sorted_marks[:5])

print("\nBottom 5 marks across all students and subjects:")
print(sorted_marks[-5:])

# Find percentile — what mark is at 75th percentile?
p75 = np.percentile(all_marks, 75)
print(f"\n75th percentile mark: {p75}")
print(f"Students above 75th percentile: {np.sum(all_marks > p75)}")

Top 5 marks across all students and subjects:
[95 92 91 90 88]

Bottom 5 marks across all students and subjects:
[72 70 68 65 60]

75th percentile mark: 88.0
Students above 75th percentile: 4


Example 4 — Flatten for Histogram Data

In [ ]:
import numpy as np

np.random.seed(12)

# 10 students × 5 subjects
marks = np.random.randint(40, 101, size=(10, 5))
print("Marks matrix:")
print(marks)

# For plotting a distribution of all marks, need flat array
all_marks = marks.flatten()
print("\nFlattened for analysis:")
print(all_marks)

# Grade distribution across all marks
print("\nGrade distribution:")
print("A+ (90-100):", np.sum(all_marks >= 90))
print("A  (80-89):", np.sum((all_marks >= 80) & (all_marks < 90)))
print("B+ (70-79):", np.sum((all_marks >= 70) & (all_marks < 80)))
print("B  (60-69):", np.sum((all_marks >= 60) & (all_marks < 70)))
print("C  (50-59):", np.sum((all_marks >= 50) & (all_marks < 60)))
print("F  (below 50):", np.sum(all_marks < 50))

Marks matrix:
[[51 67 46 89 42]
 [43 43 52 88 62]
 [89 92 45 53 65]
 [74 51 94 50 40]
 [93 80 52 53 58]
 [65 75 76 75 73]
 [70 95 72 58 62]
 [90 56 60 46 99]
 [85 49 85 70 88]
 [72 86 67 99 65]]

Flattened for analysis:
[51 67 46 89 42 43 43 52 88 62 89 92 45 53 65 74 51 94 50 40 93 80 52 53
 58 65 75 76 75 73 70 95 72 58 62 90 56 60 46 99 85 49 85 70 88 72 86 67
 99 65]

Grade distribution:
A+ (90-100): 7
A  (80-89): 8
B+ (70-79): 9
B  (60-69): 8
C  (50-59): 10
F  (below 50): 8


Example 5 — Flatten in Data Preprocessing

In [ ]:
import numpy as np

# Scenario: you received weekly sales data as a 2D array
# 4 weeks × 7 days = monthly sales
weekly_sales = np.array([
    [1200, 1500, 1100, 1800, 2100, 2500, 1900],   # Week 1
    [1300, 1400, 1200, 1700, 2000, 2400, 1800],   # Week 2
    [1100, 1600, 1300, 1900, 2200, 2600, 2000],   # Week 3
    [1250, 1450, 1150, 1750, 2050, 2450, 1950]    # Week 4
])

print("Weekly sales (4 weeks × 7 days):")
print(weekly_sales)

# Flatten to get all 28 days in sequence
daily_sales = weekly_sales.flatten()
print("\nAll 28 days in sequence:")
print(daily_sales)

print("\nMonthly statistics:")
print(f"Total monthly sales: Rs {daily_sales.sum():,}")
print("Average daily sales: Rs", int(daily_sales.mean()))
print("Best day sales: Rs", daily_sales.max())
print("Worst day sales: Rs", daily_sales.min())
print("Day number with best sales:", daily_sales.argmax() + 1)

Weekly sales (4 weeks × 7 days):
[[1200 1500 1100 1800 2100 2500 1900]
 [1300 1400 1200 1700 2000 2400 1800]
 [1100 1600 1300 1900 2200 2600 2000]
 [1250 1450 1150 1750 2050 2450 1950]]

All 28 days in sequence:
[1200 1500 1100 1800 2100 2500 1900 1300 1400 1200 1700 2000 2400 1800
 1100 1600 1300 1900 2200 2600 2000 1250 1450 1150 1750 2050 2450 1950]

Monthly statistics:
Total monthly sales: Rs 48,650
Average daily sales: Rs 1737
Best day sales: Rs 2600
Worst day sales: Rs 1100
Day number with best sales: 20


Program f — Transpose of a NumPy Array

Example 1 — Student Marks Transpose

How can you transpose student marks data from a student-subject view to a subject-student view and calculate subject averages?

In [ ]:
import numpy as np

# Original: rows = students, columns = subjects
marks = np.array([[85, 92, 78],
                  [70, 65, 90],
                  [95, 88, 76],
                  [60, 72, 68]])

print("Original (students × subjects):")
print(marks)
print("Shape:", marks.shape, "→ 4 students, 3 subjects")

marks_T = marks.T
print("\nTransposed (subjects × students):")
print(marks_T)
print("Shape:", marks_T.shape, "→ 3 subjects, 4 students")

print("\nNow each ROW is a subject:")
subject_names = ["Maths", "Physics", "Chemistry"]
for i, subject in enumerate(subject_names):
    print(f"  {subject} scores: {marks_T[i]} → average: {marks_T[i].mean():.1f}")

Original (students × subjects):
[[85 92 78]
 [70 65 90]
 [95 88 76]
 [60 72 68]]
Shape: (4, 3) → 4 students, 3 subjects

Transposed (subjects × students):
[[85 70 95 60]
 [92 65 88 72]
 [78 90 76 68]]
Shape: (3, 4) → 3 subjects, 4 students

Now each ROW is a subject:
  Maths scores: [85 70 95 60] → average: 77.5
  Physics scores: [92 65 88 72] → average: 79.2
  Chemistry scores: [78 90 76 68] → average: 78.0


Example 2 — Monthly Revenue Transpose

How can you transpose monthly revenue data from a month-product view to a product-month view to analyze product performance?

In [ ]:
import numpy as np

# Original: rows = months (12), columns = products (4)
np.random.seed(18)
revenue = np.random.randint(50000, 200000, size=(12, 4))

print("Original shape (months × products):", revenue.shape)
print("First 3 months:")
print(revenue[:3])

revenue_T = revenue.T
print("\nTransposed shape (products × months):", revenue_T.shape)
print("Product 1 revenue across all 12 months:")
print(revenue_T[0])
print("Product 1 total annual revenue:", revenue_T[0].sum())
print("Product 1 best month revenue:", revenue_T[0].max())

Example 3 — Transpose for Column Operations

How can you perform column-wise operations on a 2D array, such as calculating subject averages, using both the `axis` parameter and array transposition?

In [ ]:
import numpy as np

data = np.array([[85, 92, 78, 88],
                 [70, 65, 90, 82],
                 [95, 88, 76, 91]])

print("Original data:")
print(data)

# Subject-wise statistics (operating on columns)
# Method 1: using axis
print("\nSubject averages (axis=0):", data.mean(axis=0))

# Method 2: using transpose — sometimes more intuitive
print("Subject averages (via transpose):", data.T.mean(axis=1))

# Both give same result — shows two approaches to same problem
print("Are they equal?", np.allclose(data.mean(axis=0), data.T.mean(axis=1)))

Example 4 — Transpose to Align for Multiplication

How can you calculate the weighted average of student marks across multiple subjects using NumPy's broadcasting capabilities?

In [ ]:
import numpy as np

# student marks: 3 students × 5 subjects
marks = np.array([[85, 92, 78, 88, 76],
                  [70, 65, 90, 82, 79],
                  [95, 88, 76, 91, 84]])

# subject weights (5 weights for 5 subjects)
weights = np.array([0.25, 0.20, 0.20, 0.20, 0.15])

print("Marks shape:", marks.shape)
print("Weights shape:", weights.shape)

# Weighted average for each student
# marks is (3,5), weights is (5,) → broadcasting works
weighted_scores = marks * weights   # broadcasts weights across rows
weighted_average = weighted_scores.sum(axis=1)

print("\nWeighted average per student:")
for i, score in enumerate(weighted_average):
    print(f"  Student {i+1}: {score:.1f}")

Example 5 — Double Transpose Returns Original

What happens when you transpose a NumPy array twice, and how can you verify if it returns the original array?

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Original:")
print(arr)
print("Shape:", arr.shape)

transposed = arr.T
print("\nTransposed:")
print(transposed)
print("Shape:", transposed.shape)

double_transposed = arr.T.T
print("\nDouble transposed (should equal original):")
print(double_transposed)
print("Shape:", double_transposed.shape)
print("Equal to original?", np.array_equal(arr, double_transposed))