<a href="https://colab.research.google.com/github/ashokteja123/Data-Analysis-Essentials/blob/main/Week_3_DAE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Resources
WEEK 3 — Expanding, Squeezing, Sorting
Explanation of the Concept Before Week 3 Programming
Expanding and Squeezing are about changing the NUMBER of dimensions
without changing the data values.

Different from reshape:
  Reshape changes how values are arranged
  Expand/squeeze changes how many dimension labels exist

Why would you want to ADD a dimension?
  Machine learning models often require specific shapes.
  An image might be (28, 28) but the model expects (1, 28, 28)
  or (28, 28, 1).
  The 1 is not extra data — it is a dimension label.

Why would you want to REMOVE a dimension?
  After processing, you might have shape (1, 5) but need (5,).
  Squeeze removes the size-1 dimensions.

Think of it like:
  expand_dims: add a new empty axis (size 1) at any position
  squeeze: remove all axes that have size 1

### Program a — Expanding a NumPy Array
The Math Intuition on Board
`np.expand_dims(arr, axis=n)`
  Inserts a new axis at position n.
  The new axis has size 1.
  Total elements do not change.
  Only shape changes.

Example:
  `arr` shape: (5,)
  `expand_dims(arr, axis=0)` → shape (1, 5)
  `expand_dims(arr, axis=1)` → shape (5, 1)

Example 2:
  `arr` shape: (3, 4)
  `expand_dims(arr, axis=0)` → shape (1, 3, 4)
  `expand_dims(arr, axis=2)` → shape (3, 4, 1)

The number of elements: 12 in all cases.
Only the labeling of dimensions changes.

#### Example 1 — Student Marks Expand for ML

In [1]:
import numpy as np

# One student's marks in 5 subjects
student_marks = np.array([85, 92, 78, 88, 76])
print("Original marks:", student_marks)
print("Shape:", student_marks.shape)

# ML model expects batch of samples: (batch_size, features)
# We have 1 student, 5 features
marks_as_batch = np.expand_dims(student_marks, axis=0)
print("\nExpanded for ML batch input:")
print(marks_as_batch)
print("Shape:", marks_as_batch.shape)
print("Meaning: 1 sample with 5 features")

# Different expansion — features as column vector
marks_as_column = np.expand_dims(student_marks, axis=1)
print("\nExpanded as column vector:")
print(marks_as_column)
print("Shape:", marks_as_column.shape)
print("Meaning: 5 rows, 1 column")

Original marks: [85 92 78 88 76]
Shape: (5,)

Expanded for ML batch input:
[[85 92 78 88 76]]
Shape: (1, 5)
Meaning: 1 sample with 5 features

Expanded as column vector:
[[85]
 [92]
 [78]
 [88]
 [76]]
Shape: (5, 1)
Meaning: 5 rows, 1 column


#### Example 2 — Image Preprocessing Concept

In [2]:
import numpy as np

# Grayscale image: height × width (2D)
grayscale_image = np.random.randint(0, 256, size=(28, 28))
print("Grayscale image shape:", grayscale_image.shape)

# Add batch dimension: (1, height, width)
batch_image = np.expand_dims(grayscale_image, axis=0)
print("With batch dimension:", batch_image.shape)

# Add channel dimension: (height, width, 1)
channel_image = np.expand_dims(grayscale_image, axis=2)
print("With channel dimension:", channel_image.shape)

# Add both: (1, height, width, 1)
full_image = np.expand_dims(np.expand_dims(grayscale_image, axis=0), axis=3)
print("With batch and channel:", full_image.shape)

print("\nAll arrays contain the same 784 pixel values")
print("Verification:", grayscale_image.size, batch_image.size,
      channel_image.size, full_image.size)

Grayscale image shape: (28, 28)
With batch dimension: (1, 28, 28)
With channel dimension: (28, 28, 1)
With batch and channel: (1, 28, 28, 1)

All arrays contain the same 784 pixel values
Verification: 784 784 784 784


#### Example 3 — Expanding for Broadcasting Alignment

In [3]:
import numpy as np

# Monthly sales for 4 products (1D array)
monthly_sales = np.array([15000, 22000, 18000, 25000])

# Discount rates for 3 months (1D array)
discount_rates = np.array([0.05, 0.10, 0.15])

# To compute discounted sales for each product × each month
# Need to broadcast: (4,) and (3,) won't work directly
# Solution: expand dimensions

sales_col = np.expand_dims(monthly_sales, axis=1)    # shape (4, 1)
discount_row = np.expand_dims(discount_rates, axis=0) # shape (1, 3)

print("Sales column shape:", sales_col.shape)
print("Discount row shape:", discount_row.shape)

# Now broadcasting works: (4, 1) × (1, 3) → (4, 3)
discounted = sales_col * discount_row
print("\nDiscounted amounts (4 products × 3 discount rates):")
print(discounted)
print("Shape:", discounted.shape)

Sales column shape: (4, 1)
Discount row shape: (1, 3)

Discounted amounts (4 products × 3 discount rates):
[[ 750. 1500. 2250.]
 [1100. 2200. 3300.]
 [ 900. 1800. 2700.]
 [1250. 2500. 3750.]]
Shape: (4, 3)


#### Example 4 — Temperature Data Expansion

In [4]:
import numpy as np

# Daily max temperatures for 7 days
daily_max = np.array([32, 34, 31, 35, 33, 36, 30])
print("Daily max temps:", daily_max)
print("Shape:", daily_max.shape)

# Expand to represent multiple cities (will fill with same data as demo)
# In real use case, you would stack different city data
expanded = np.expand_dims(daily_max, axis=0)
print("\nExpanded (1 city row):", expanded.shape)

# Stack for 3 cities
city_data = np.vstack([expanded * 1.0,
                        expanded * 0.95,
                        expanded * 1.05])
print("3 cities × 7 days:", city_data.shape)
print(city_data.round(1))

Daily max temps: [32 34 31 35 33 36 30]
Shape: (7,)

Expanded (1 city row): (1, 7)
3 cities × 7 days: (3, 7)
[[32.  34.  31.  35.  33.  36.  30. ]
 [30.4 32.3 29.4 33.2 31.4 34.2 28.5]
 [33.6 35.7 32.6 36.8 34.6 37.8 31.5]]


#### Example 5 — Expand Then Operate

In [5]:
import numpy as np

# Exam marks for one student (1D)
student = np.array([85, 92, 78, 88, 76])

# Expand to 2D row
student_2d = np.expand_dims(student, axis=0)
print("Student as 2D row:", student_2d.shape)
print(student_2d)

# Now can use 2D operations
print("Row-wise mean:", student_2d.mean(axis=1))     # mean of this student
print("Col-wise — each subject on its own:", student_2d.mean(axis=0))

# Expand to column
student_col = np.expand_dims(student, axis=1)
print("\nStudent as column:", student_col.shape)
print(student_col)

Student as 2D row: (1, 5)
[[85 92 78 88 76]]
Row-wise mean: [83.8]
Col-wise — each subject on its own: [85. 92. 78. 88. 76.]

Student as column: (5, 1)
[[85]
 [92]
 [78]
 [88]
 [76]]


### Program b — Squeezing a NumPy Array
The Math Intuition on Board
`squeeze()` = remove ALL axes with size 1

Before squeeze:  shape (1, 5, 1)
After squeeze:   shape (5,)

Both size-1 dimensions removed.
The 5 elements remain.

Before squeeze:  shape (3, 1, 4)
After squeeze:   shape (3, 4)
Only the size-1 middle axis removed.

Before squeeze:  shape (3, 4)
After squeeze:   shape (3, 4)
Nothing to remove. Shape unchanged.

When does squeeze help?
  After expand_dims operations
  When loading data from files that add extra dimensions
  When model output is (1, 1) but you want a scalar
  When intermediate processing creates unnecessary size-1 axes

#### Example 1 — Basic Squeeze

In [6]:
import numpy as np

# Array with unnecessary size-1 dimensions
a = np.array([[[85, 92, 78, 88, 76]]])  # shape (1, 1, 5)
print("Original shape:", a.shape)
print("Original array:", a)

b = np.squeeze(a)
print("\nAfter squeeze shape:", b.shape)
print("Squeezed array:", b)

# Verify same data
print("Same elements?", np.array_equal(a.flatten(), b.flatten()))

Original shape: (1, 1, 5)
Original array: [[[85 92 78 88 76]]]

After squeeze shape: (5,)
Squeezed array: [85 92 78 88 76]
Same elements? True


#### Example 2 — Squeeze After Expand

In [7]:
import numpy as np

original = np.array([10, 20, 30, 40, 50])
print("Original:", original, "| Shape:", original.shape)

# Expand and then squeeze — should return to original
expanded = np.expand_dims(original, axis=0)
print("Expanded:", expanded.shape)

squeezed_back = np.squeeze(expanded)
print("Squeezed back:", squeezed_back, "| Shape:", squeezed_back.shape)
print("Matches original?", np.array_equal(original, squeezed_back))

Original: [10 20 30 40 50] | Shape: (5,)
Expanded: (1, 5)
Squeezed back: [10 20 30 40 50] | Shape: (5,)
Matches original? True


#### Example 3 — Squeeze Specific Axis

In [8]:
import numpy as np

arr = np.zeros((3, 1, 4, 1))   # two size-1 axes
print("Original shape:", arr.shape)

# Squeeze all size-1 axes
fully_squeezed = np.squeeze(arr)
print("Fully squeezed:", fully_squeezed.shape)

# Squeeze only axis 1
partial_squeeze = np.squeeze(arr, axis=1)
print("Squeeze only axis 1:", partial_squeeze.shape)

# Squeeze only axis 3
partial_squeeze2 = np.squeeze(arr, axis=3)
print("Squeeze only axis 3:", partial_squeeze2.shape)

Original shape: (3, 1, 4, 1)
Fully squeezed: (3, 4)
Squeeze only axis 1: (3, 4, 1)
Squeeze only axis 3: (3, 1, 4)


#### Example 4 — Practical Squeeze After Computation

In [9]:
import numpy as np

# Marks of 5 students in 1 subject (after column selection from 2D)
marks_2d = np.array([[85], [70], [95], [60], [88]])  # shape (5, 1)
print("Column from dataset:", marks_2d.shape)
print(marks_2d)

# Squeeze to 1D for easy processing
marks_1d = np.squeeze(marks_2d)
print("\nAfter squeeze:", marks_1d.shape)
print(marks_1d)

print("Average:", marks_1d.mean())
print("Above 80:", marks_1d[marks_1d > 80])

Column from dataset: (5, 1)
[[85]
 [70]
 [95]
 [60]
 [88]]

After squeeze: (5,)
[85 70 95 60 88]
Average: 79.6
Above 80: [85 95 88]


#### Example 5 — Squeeze with Conditions

In [10]:
import numpy as np

# Different shapes and squeeze behavior
shapes_to_test = [
    np.zeros((1, 5)),
    np.zeros((5, 1)),
    np.zeros((1, 5, 1)),
    np.zeros((3, 4)),      # no size-1 axis — unchanged
    np.zeros((1, 1, 1))    # all size-1 — becomes scalar
]

print("Squeeze behavior with different shapes:")
print(f"{'Original Shape':<20} {'After Squeeze':<20}")
print("-" * 40)
for arr in shapes_to_test:
    squeezed = np.squeeze(arr)
    print(f"{str(arr.shape):<20} {str(squeezed.shape):<20}")

Squeeze behavior with different shapes:
Original Shape       After Squeeze       
----------------------------------------
(1, 5)               (5,)                
(5, 1)               (5,)                
(1, 5, 1)            (5,)                
(3, 4)               (3, 4)              
(1, 1, 1)            ()                  


### Program c — Sorting in NumPy Arrays
The Math Intuition on Board
Sorting = arranging values in order (ascending or descending)

Two types of sorting in NumPy:

1. `np.sort(arr)` → returns SORTED VALUES
   Input:  `[85, 92, 78, 88, 76]`
   Output: `[76, 78, 85, 88, 92]`
   You get the values in order.

2. `np.argsort(arr)` → returns SORTED INDICES
   Input:  `[85, 92, 78, 88, 76]`
   Output: `[4,  2,  0,  3,  1]`
   You get the POSITIONS that would sort the array.
   Position 4 (value 76) comes first (smallest)
   Position 2 (value 78) comes second
   etc.

Why is `argsort` useful?
  You sort by one column but want to rearrange another.
  Example: Sort students by marks to find their rank order.
  `argsort` gives you the rank positions.
  Use those positions to also sort their names.

Axis in 2D sorting:
  `axis=0` → sort within each COLUMN (sort down each column separately)
  `axis=1` → sort within each ROW (sort across each row separately)
Draw this on board:
Original 2D:          Sort axis=0:         Sort axis=1:
85  92  78            70  65  78           78  85  88  92
70  65  90            85  88  90           65  70  82  90
95  88  82            95  92  82           82  88  95

Each column sorted     Each row sorted
independently         independently

#### Example 1 — Sort Student Marks

In [11]:
import numpy as np

marks = np.array([85, 92, 78, 88, 76, 90, 82, 95, 71, 88])
print("Original marks:", marks)

# Ascending order
ascending = np.sort(marks)
print("Ascending:", ascending)

# Descending order (sort then reverse)
descending = np.sort(marks)[::-1]
print("Descending:", descending)

# Find ranks using argsort
# argsort gives indices that would sort the array
rank_order = np.argsort(marks)[::-1]   # descending rank
print("\nRank order (index positions):", rank_order)
print("Meaning: student at position", rank_order[0], "scored highest (", marks[rank_order[0]], ")")

# Assign ranks 1 to 10
ranks = np.argsort(np.argsort(marks)[::-1]) + 1
print("Student ranks:", ranks)

Original marks: [85 92 78 88 76 90 82 95 71 88]
Ascending: [71 76 78 82 85 88 88 90 92 95]
Descending: [95 92 90 88 88 85 82 78 76 71]

Rank order (index positions): [7 1 5 9 3 0 6 2 4 8]
Meaning: student at position 7 scored highest ( 95 )
Student ranks: [ 6  2  8  5  9  3  7  1 10  4]


#### Example 2 — Sort with Names Using argsort

In [12]:
import numpy as np

names = np.array(["Ravi", "Priya", "Arjun", "Kavita", "Suresh",
                   "Anita", "Mohan", "Deepa", "Kiran", "Lakshmi"])
marks = np.array([85, 92, 78, 88, 76, 90, 82, 95, 71, 88])

print("Students and marks:")
for name, mark in zip(names, marks):
    print(f"  {name}: {mark}")

# Sort by marks descending
sort_indices = np.argsort(marks)[::-1]
sorted_names = names[sort_indices]
sorted_marks = marks[sort_indices]

print("\nRanking (best to worst):")
for rank, (name, mark) in enumerate(zip(sorted_names, sorted_marks), 1):
    print(f"  Rank {rank}: {name} — {mark} marks")

Students and marks:
  Ravi: 85
  Priya: 92
  Arjun: 78
  Kavita: 88
  Suresh: 76
  Anita: 90
  Mohan: 82
  Deepa: 95
  Kiran: 71
  Lakshmi: 88

Ranking (best to worst):
  Rank 1: Deepa — 95 marks
  Rank 2: Priya — 92 marks
  Rank 3: Anita — 90 marks
  Rank 4: Lakshmi — 88 marks
  Rank 5: Kavita — 88 marks
  Rank 6: Ravi — 85 marks
  Rank 7: Mohan — 82 marks
  Rank 8: Arjun — 78 marks
  Rank 9: Suresh — 76 marks
  Rank 10: Kiran — 71 marks


#### Example 3 — Sort 2D Array

In [13]:
import numpy as np

marks_2d = np.array([[85, 92, 78, 88],
                      [70, 65, 90, 82],
                      [95, 88, 76, 91]])

print("Original marks (3 students × 4 subjects):")
print(marks_2d)

# Sort each row (each student's marks sorted)
row_sorted = np.sort(marks_2d, axis=1)
print("\nEach row sorted (each student's marks in order):")
print(row_sorted)

# Sort each column (rank students per subject)
col_sorted = np.sort(marks_2d, axis=0)
print("\nEach column sorted (ranking within each subject):")
print(col_sorted)
print("Top score per subject:", col_sorted[-1])

Original marks (3 students × 4 subjects):
[[85 92 78 88]
 [70 65 90 82]
 [95 88 76 91]]

Each row sorted (each student's marks in order):
[[78 85 88 92]
 [65 70 82 90]
 [76 88 91 95]]

Each column sorted (ranking within each subject):
[[70 65 76 82]
 [85 88 78 88]
 [95 92 90 91]]
Top score per subject: [95 92 90 91]


#### Example 4 — Sort IPL Scores with Team Names

In [14]:
import numpy as np

teams = np.array(["CSK", "MI", "RCB", "KKR", "SRH", "DC", "PBKS", "RR"])
avg_scores = np.array([178, 182, 165, 175, 170, 168, 172, 176])

print("Team averages:")
for team, score in zip(teams, avg_scores):
    print(f"  {team}: {score}")

# Sort by score descending
sort_idx = np.argsort(avg_scores)[::-1]
print("\nIPL Teams Rankings by Batting Average:")
for rank, idx in enumerate(sort_idx, 1):
    print(f"  {rank}. {teams[idx]}: {avg_scores[idx]}")

Team averages:
  CSK: 178
  MI: 182
  RCB: 165
  KKR: 175
  SRH: 170
  DC: 168
  PBKS: 172
  RR: 176

IPL Teams Rankings by Batting Average:
  1. MI: 182
  2. CSK: 178
  3. RR: 176
  4. KKR: 175
  5. PBKS: 172
  6. SRH: 170
  7. DC: 168
  8. RCB: 165


#### Example 5 — Sort Loan Applications by Amount

In [15]:
import numpy as np

np.random.seed(30)
loan_ids = np.arange(1001, 1011)
loan_amounts = np.random.randint(50000, 500000, 10)
credit_scores = np.random.randint(600, 850, 10)

print("Loan Applications (unsorted):")
print(f"{'ID':<8} {'Amount':>12} {'Credit Score':>14}")
print("-" * 36)
for lid, amt, cs in zip(loan_ids, loan_amounts, credit_scores):
    print(f"{lid:<8} Rs {amt:>10,} {cs:>13}")

# Sort by loan amount
sort_idx = np.argsort(loan_amounts)[::-1]
print("\nSorted by Loan Amount (High to Low):")
print(f"{'ID':<8} {'Amount':>12} {'Credit Score':>14}")
print("-" * 36)
for idx in sort_idx:
    print(f"{loan_ids[idx]:<8} Rs {loan_amounts[idx]:>10,} {credit_scores[idx]:>13}")

# Find top 3 loan amounts
print("\nTop 3 loan amounts:", loan_amounts[sort_idx[:3]])
print("Average of bottom 3:", loan_amounts[sort_idx[-3:]].mean())

Loan Applications (unsorted):
ID             Amount   Credit Score
------------------------------------
1001     Rs    481,909           607
1002     Rs     98,045           719
1003     Rs    410,948           665
1004     Rs     96,220           777
1005     Rs    378,599           773
1006     Rs    408,197           789
1007     Rs    497,633           763
1008     Rs    459,006           618
1009     Rs    272,339           618
1010     Rs    158,969           844

Sorted by Loan Amount (High to Low):
ID             Amount   Credit Score
------------------------------------
1007     Rs    497,633           763
1001     Rs    481,909           607
1008     Rs    459,006           618
1003     Rs    410,948           665
1006     Rs    408,197           789
1005     Rs    378,599           773
1009     Rs    272,339           618
1010     Rs    158,969           844
1002     Rs     98,045           719
1004     Rs     96,220           777

Top 3 loan amounts: [497633 481909 459006]


### The Week 3 Final Thought — Connect All Three

In [16]:
import numpy as np

# Mini capstone: put expand, squeeze, and sort together
# Student exam scores received as 2D with unnecessary dimension
raw_data = np.array([[[85, 92, 78, 88, 76],
                       [70, 65, 90, 82, 79],
                       [95, 88, 76, 91, 84]]])

print("Raw data shape (as received):", raw_data.shape)

# Step 1: Squeeze unnecessary dimension
marks = np.squeeze(raw_data)
print("After squeeze:", marks.shape)

# Step 2: Calculate averages per student
student_avg = marks.mean(axis=1)
print("Student averages:", student_avg.round(1))

# Step 3: Sort students by average
sort_idx = np.argsort(student_avg)[::-1]
print("Student ranking (best to worst):")
for rank, idx in enumerate(sort_idx, 1):
    print(f"  Rank {rank}: Student {idx+1} — Average {student_avg[idx]:.1f}")

# Step 4: Expand for next processing step (feeding into ML model)
ranked_marks = marks[sort_idx]
ml_ready = np.expand_dims(ranked_marks, axis=0)
print("\nML-ready shape:", ml_ready.shape)
print("3 students (ranked), 5 subjects, in a batch of 1")
# This shows the natural pipeline: receive messy-shaped data → squeeze → analyze → sort → expand for next step. That is real data engineering work.

Raw data shape (as received): (1, 3, 5)
After squeeze: (3, 5)
Student averages: [83.8 77.2 86.8]
Student ranking (best to worst):
  Rank 1: Student 3 — Average 86.8
  Rank 2: Student 1 — Average 83.8
  Rank 3: Student 2 — Average 77.2

ML-ready shape: (1, 3, 5)
3 students (ranked), 5 subjects, in a batch of 1
